### ISSUE TITLE
Create Summary Pages

### ISSUE THREAD

**Issue by KianBadie** [KianBadie/cell-atlas#13]
Create summary pages at the end of each chapter.

How they currently look:
![Peek 2020-12-06 20-09](https://user-images.githubusercontent.com/18221058/101308630-290f7880-37ff-11eb-9d26-fb073ab7a739.gif)

**Comment by KianBadie** [comment]
@coiko I created something to work with for the summary pages. What do you think of this current layout? I added underlines to the subheadings because I felt like it was hard to distinguish without them since all the text was white. The left video would be the associated media for the summary page. Which leads me to my next question, are all gifs going to be videos for the site? I know we had this conversation a while ago about the schematic gifs and replacing them with videos. Does that apply to all gifs on the site? 

## Screenshot:
![Screenshot from 2020-12-06 20-51-21](https://user-images.githubusercontent.com/18221058/101310944-0f712f80-3805-11eb-8c8d-dc81f38880e1.png)

**Comment by coiko** [comment]
Thanks @KianBadie!  This looks great!  I really like the underlined headings to distinguish the subsections.

Good question about the gifs.  All the Learn More content is videos now, but I think we might want to keep the summaries as gifs, at least for now.  Ultimately, like the phylogenetic tree, I'd like to make them more interactive, where the different sections would highlight/expand as the reader hovers over them instead of just looping automatically.  So with that in mind, would it make more sense and/or be easier to style the summary page like the appendix pages, with just a single full-width dark-grey page with the image (gif for now, jpg/svg/however-that-would-work later) at the top and the text below?  (Just like the Phylogenetic Tree page but with an inverted order of text/graphic).  The only difference from the Appendix would be that it would still have the previous/next navigation arrows.  If it's easier to keep this format, though, and the video section can be repurposed for a gif, we should go with that.  What do you think?

**Comment by KianBadie** [comment]
@coiko Great, glad you like it!

And I see. Yeah, if this layout is preferred we could stick with it and easily display the gif in place of the video. It would also be easier, but if you prefer the appendix layout for the summary pages it also would not be a big deal to implement! It sounded like you preferred the current layout, but I just wanted to double check which one is preferred.

**Comment by coiko** [comment]
Thanks @KianBadie!  Then yes, let's stick with this layout!  

Also, the more I think about it, the more I like the idea of replacing these gifs with mp4s.  As we discussed, they're more lightweight for the site and it might be easier for the reader/viewer until we get something they can play with.  So scratch what I said about gifs and I'll make them into mp4s.

**Comment by KianBadie** [comment]
@coiko Sounds good, mp4s it is! I think another added benefit of videos is that someone could pause and replay certain sections rather than waiting for it to replay as well.

**Comment by KianBadie** [comment]
@coiko Sorry for doing this late. I noticed the break tags in the summary pages and I was wondering if that was for the purpose of modifying their layout? If so, I'll go ahead and add that to styling of the page itself so it will always be there!

## Screenshot
![Screenshot from 2020-12-15 21-12-23](https://user-images.githubusercontent.com/18221058/102307926-5bfdee80-3f1a-11eb-8007-a18a81de86ff.png)

**Comment by coiko** [comment]
@KianBadie Yes, it was indeed to make the layout a little easier to read, and yes, that would be a much smarter way to do it!  Thanks!

**Comment by KianBadie** [comment]
@coiko Sounds good, no problem!

**Comment by KianBadie** [comment]
@coiko I assumed the amount of spacing in the above picture was due to the inability to use the styling. I added a smaller amount of space but please let me know if what was pictured above is intended! What do you think of this amount of space? And sorry if this feels last minute. I told myself at 3pm I would send the files over so I was just doing this because there was some time!

![Screenshot from 2020-12-16 14-12-41](https://user-images.githubusercontent.com/18221058/102412905-f86ed200-3fa8-11eb-9fda-797fd66941d9.png)

**Comment by coiko** [comment]
@KianBadie Oh that's so perfect!  (And yes, the brute force method definitely made too much space.)  And don't apologize for making things more and more awesome!

**Comment by KianBadie** [comment]
@coiko Terrific! And noted, thank you!
