### ISSUE TITLE
Implement "learn more" modal windows

### ISSUE THREAD

**Issue by KianBadie** [KianBadie/cell-atlas#8]
Implement modal windows that open when "learn more" button is clicked. Modal window should contain:
- [ ] Associated video/graphic
- [ ] Subsection title
- [ ] Subsection material

Screenshot from Mockup:
![Screenshot from 2020-11-18 13-42-53](https://user-images.githubusercontent.com/18221058/99591674-ff9fc180-29a3-11eb-8f74-7095a4d2b9b5.png)

**Comment by KianBadie** [comment]
Current Progress: There is a prototype modal window that opens up when a subsection is clicked. The content of these modal windows are based off of markdown files that contain only material/metadata of the subsection itself.
![Peek 2020-11-18 13-44](https://user-images.githubusercontent.com/18221058/99591869-42619980-29a4-11eb-89f3-8352c9f490de.gif)

**Comment by KianBadie** [comment]
Current questions:
1. Is it desired for the gifs to play on an infinite loop?

**Comment by coiko** [comment]
Good question.  It's definitely not ideal as is (we had them on an infinite loop but Grant didn't like it so we switched to single play and it's on my to-do list to figure out a better format).  We were using gifs because they worked well with the bookdown project setup, but I've been wondering if it wouldn't be better to go with .mp4 files instead.  The files should be small, we wouldn't be constrained on length, and we can have a play-on-click behavior which would probably be better than the gif options.  What do you think?

**Comment by KianBadie** [comment]
@coiko Interesting, your question made me research the tradeoffs between gifs vs videos and I found some interesting results. After some quick reading, it seems that videos are encouraged over using gifs. Below is a screenshots of Google's Lighthouse assessment of the current section page. The screenshots says "mpeg4" videos, but they are the same as .mp4 videos.

![Screenshot from 2020-11-19 09-40-05](https://user-images.githubusercontent.com/18221058/99702890-3d0b5a00-2a4b-11eb-9cba-de913ca0e424.png)

I will look more into this, because it seems like videos have significant benefits over gifs (playback controls, possibly smaller, not constrained by length,...). When you make the gifs, do they start out as .mp4 files, and then they are converted to the .gif format using some program?

**Comment by coiko** [comment]
Then it definitely looks like videos are the way to go!  It works better for the content, too, since we won't have the same length constraint for file size.  I do make the videos as .mp4 first and then convert to .gif (using Photoshop, after some trial and error with other programs), so we can just use the .mp4 files instead.

What's the best way to transfer files like this to you?  Should I replace the files in the main cell-atlas GitHub project so you can pull them from there or should I just send you a compressed directory by email/file-share service?

**Comment by KianBadie** [comment]
@coiko sounds good! Emailing me the compressed directory would be convenient! Before that, I would double the size difference between the mp4 and gif files for a given video just to make sure the file size really is smaller. From the stuff I have been reading online, I am not sure as of right now if the file is only smaller when converting from gif to mp4, rather than starting with an mp4 file. If the file you check is indeed smaller on the mp4 format, then I guess no other steps are needed and I would be happy to take them all! If not, then no worries and I will look into what needs to be done in order to get what we want.

**Comment by coiko** [comment]
@KianBadie I have a quick question about the Learn More subsections:
Do the subsection titles need to be globally unique, or are they referenced by the section they're in so that there could be, for instance, a "Structure" button in Section 2.5 and a "Structure" button in Section 7.2 that would be different?  (I'm shortening the titles to try to keep the button size reasonable.)

**Comment by KianBadie** [comment]
@coiko If you are referencing the `title` metadata field in the markdown file, then the titles do not have to be unique, even if it is in the same section. The thing that makes a subsection unique are the values in the `subsections` field list, which are the file names of the subsections without the file type extension. So really, the only thing that needs to be unique is the file name.

So it would be just fine to have the "Structure" buttons scenario you described! The values for the `title` field won't cause any problems if there are duplicates anywhere.

**Comment by coiko** [comment]
Great - thanks @KianBadie!

**Comment by KianBadie** [comment]
@coiko I'm going to add the metadata for the schematics today (as well as the gray citation bar at the bottom of the more/schematic media. I'll be posting the progress in this issue). I noticed that in some of the sources are citations ("[@...]"). In the gray bars, did you want those to appear as the actual references in the citation bar? So the citation would look something like `Source: [52]`. The "More's" currently have the collectors metadata stored as plain text  (which I am assuming is like the source).

**Comment by KianBadie** [comment]
Also, is this what you were thinking for how the bar would display? I'm implementing it in a way where the code assumes a couple of things. Please correct any of these assumptions:
- For "More" types: If there is something to cite, there will always be at least a `collector` field
- For "Schematics" types: If there is something to cite, there will always be at least a `source` field
- `collector` field will only be used for "More" types while `source` fields will only be used for schematics.

## Screenshot
![Screenshot from 2020-12-09 14-47-11](https://user-images.githubusercontent.com/18221058/101697902-7a04b400-3a2d-11eb-9807-75d05b76b57c.png)

**Comment by coiko** [comment]
@KianBadie It's perfect!  I love the display, and yes, the implementation of which fields to show for the two video types is exactly right.  And as for the "Source" for the schematic types, yes, it would be great if those would appear as formatted references exactly the way you showed.  Thanks!

Also thank you for tagging me on things.  It's fantastic to see your progress and I love seeing things as you fix them and giving input where needed, so please keep it up!

**Comment by KianBadie** [comment]
@coiko Awesome! And got it, will format the references, no problem!

And that's good to hear, I'll keep the tagging going then!

**Comment by KianBadie** [comment]
@coiko I will validate if the referencing is correct tomorrow (I was satisfied/excited enough to get this working tonight to call it a day!), but I got the references to appear to work with the metadata for the schematics. Here is how they look so far. Do you have any opinions to share on the styling of the links? I feel like they didn't look as "link-y".

![Peek 2020-12-09 22-17](https://user-images.githubusercontent.com/18221058/101729106-75abbb80-3a6c-11eb-80c7-9318ff084640.gif)

**Comment by coiko** [comment]
Thanks @KianBadie!  It looks fantastic!  

I see what you mean about the link styling.  The "Structure" field looks fine, but we could make the "Source" reference a little more expansive (especially since that will be the only field in some cases).  For instance, maybe we could show the author and date for the reference, something like "Sobti et al. (2016)".  It seems like that would be tough to do in an automatic fashion without affecting all the references in the text.  Maybe I could manually change the link text in the subsection files?  What do you think? Anyway, this is beautiful, so that's definitely a low priority.  The format and display are perfect!

**Comment by KianBadie** [comment]
@coiko Yeah I like that reference style you commented. I don't think it would be too hard to make it automatic, but like you said, I should probably add it to my "features that would be nice to implement" and get to it after tightening up some of the higher priority features. Editing the fields manually can work for now though! I posted a picture of what `"Sobti et al. (2016) [@sobti2016]"` renders to. Maybe the brackets could be white color with the rest of the text staying blue. Would you want  the references to be like that or would you want to save that for later?

I'm glad you like it overall! Just to double check, I think the reference in the grey bar and the paragraph text are both referencing `[20]`. Is this desired, since they are referencing the same thing? Or should one be `[20]` and the other `[21]`?

## Screenshot
![Screenshot from 2020-12-10 10-35-17](https://user-images.githubusercontent.com/18221058/101815092-e0441200-3ad3-11eb-8ccb-51d405475999.png)

**Comment by coiko** [comment]
@KianBadie Yes, that's exactly right (they should both cite [20] since they're referencing the same thing).  And I do like the way the longer reference looks.  Would it be possible to link to the reference directly from the "Sobti et al. (2016)" text without having to show the [20]?  That would probably be the most elegant solution.  But yes, this is great for now!

**Comment by KianBadie** [comment]
@coiko Got it! And it would! In the metadata, until we have something automatic, we could have something like "Sobti et al. (2016) [@sobti2016]" and make the link display like you described by treating the `source` metadata field differently from the other references. Would you still want it to count as a reference? Like let's say we have references `[19]`, `[20]`, `Source: Sobti et al. (2016)`, would the next one be `[21]` or `[22]`?

**Comment by coiko** [comment]
@KianBadie That would be awesome!  And good question about how to handle the source references.  All of them are also cited in the subsection text (as numbered references), so there's no need to give them their own numbers since they should link to the same (numbered) item in the reference list.  I don't know if that makes it any easier to handle?

**Comment by KianBadie** [comment]
@coiko Finally got back to wrapping up that referencing feature (I put it down for a couple days). The reference numbers are in line with the bookdown version (as shown through the 2nd and 3rd screenshots). The references also don't increment the reference numbers as described in your most recent comment. Let me know if there is anything to change or add!

## Gif
![Peek 2020-12-13 20-21](https://user-images.githubusercontent.com/18221058/102040216-f88c8900-3d80-11eb-874b-f82ab152c293.gif)
## Screenshot of very long list of references
![Screenshot from 2020-12-13 20-20-40](https://user-images.githubusercontent.com/18221058/102040238-0e9a4980-3d81-11eb-96aa-fbae0ceed505.png)
## Comparison to bookdown version
![Screenshot from 2020-12-13 20-21-01](https://user-images.githubusercontent.com/18221058/102040258-240f7380-3d81-11eb-93fd-3e64f25a5eec.png)

**Comment by coiko** [comment]
@KianBadie Ah, it's perfect!  I also really like the centered option for a long list.  Thanks so much!

**Comment by KianBadie** [comment]
@coiko No problem!

**Comment by KianBadie** [comment]
@coiko I noticed the schematics received videos fields to replace the gifs! Just wanted to give you a heads up that for the sake of simplicity in the code, I am going to rename the "graphic" field to "video" if there is an mp4 video as the value. When we sync our code to the server, we would just have to tell Robert or Tom about those new videos that we are adding so that they can push those to the server as well!

**Comment by coiko** [comment]
@KianBadie That sounds great.  Thanks so much!
