### ISSUE TITLE
Create References page

### ISSUE THREAD

**Issue by KianBadie** [KianBadie/cell-atlas#9]
Create references page based of off [AtlasBibTex.bib](https://github.com/KianBadie/cell-atlas/blob/main/AtlasBibTeX.bib) file and create links to references when mentioned in section/chapter pages. The original `AtlasBibText.bib` file is still very useful, thankfully, so no rewriting of the bibliography is needed.  

Screenshot from bookdown project:
![Screenshot from 2020-11-30 12-30-07](https://user-images.githubusercontent.com/18221058/100667915-f9003b00-330f-11eb-9cd7-404a0c5443ce.png)

**Comment by KianBadie** [comment]
@coiko I noticed that the references page seems to be in order that they are mentioned in the book. Did you want to keep that behavior/order?

**Comment by coiko** [comment]
@KianBadie I'm so glad the .bib file will make creating the bibliography easier!  And yes, it would be good to keep them in the order of mention.  Bookdown uses a pandoc function to make the references.  The default style wasn't ideal because it uses an author name and the year of publication (e.g. [Badie 2020]), which fails for websites, and it's kind of long/redundant, so I specified a different reference format with a .csl file (springer-socpsych-brackets.csl in the main folder).  That format uses numbers (e.g. [1]), which works better.  Let me know if you need any more info about that.

**Comment by KianBadie** [comment]
Sounds good and thanks for the info! So originally, the bookdown site would display references as the name/year instead of the number?

**Comment by coiko** [comment]
@KianBadie That sounds great!  Yes, it's a literal fail for citing websites where it just can't build the link because there's nothing in the publication year field in the .bib file.

And yes, I think the layout should work great for the feature index and scientist profiles as well.  I like the idea of the dark grey full-width page with text.

**Comment by KianBadie** [comment]
@coiko Ah I think I understand now. So originally it just wouldn't link to the references page if you were citing a website since it does not have a year field?

And great! I will have something to show soon.

**Comment by coiko** [comment]
@KianBadie Yes, exactly.  Thanks!

**Comment by KianBadie** [comment]
@coiko I have created a starting point for the references page and I wanted to get your opinion to see which direction to take this in. Also, please ignore the numbering of the bibliography entries and the empty nav menu, as I plan to fix those afterwards. I opened the empty nav to try to "simulate" what the nav bar would look like layout wise in regards to the reference page.

As always, all opinions/input are welcome and appreciated!

## Screenshot
![Screenshot from 2020-12-01 14-21-46](https://user-images.githubusercontent.com/18221058/100803962-e570d500-33e0-11eb-883d-fab3c6712e16.png)
## Gif
![Peek 2020-12-01 14-21](https://user-images.githubusercontent.com/18221058/100803945-dee25d80-33e0-11eb-85c1-d9c727628cc7.gif)

**Comment by coiko** [comment]
@KianBadie It's perfect!  I wouldn't change a thing.

**Comment by KianBadie** [comment]
@coiko Awesome!

**Comment by KianBadie** [comment]
The references made in the markdown (`[@<Citation ID>]`) now show up as a numbered reference and link to an entry on the reference page. The numbering of the reference is sequential (at least, it is intended to be). Will validate in the future if the numbering is correct. Also, I updated the nav menu data so the appendix pages show up in the nav!

## Tour
![Peek 2020-12-01 16-00](https://user-images.githubusercontent.com/18221058/100811070-a6e21700-33ee-11eb-86a7-fdd12ba420d6.gif)

**Comment by coiko** [comment]
@KianBadie This is fantastic!  It looks perfect.
